package it.drwolf.eloise.web.entity;

// Generated 17-giu-2008 14.55.38 by Hibernate Tools 3.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orario generated by hbm2java
 */
@Entity
@Table(name = "`Orario`", catalog = "eloise")
public class Orario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5506802968410829501L;
	private Integer idorario;
	private String descrizione;
	private Set<People> peoples = new HashSet<People>(0);
	private Set<Ufficio> ufficios = new HashSet<Ufficio>(0);

	public Orario() {
	}

	public Orario(String descrizione, Set<People> peoples, Set<Ufficio> ufficios) {
		this.descrizione = descrizione;
		this.peoples = peoples;
		this.ufficios = ufficios;
	}

	@Column(name = "Descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDOrario", unique = true, nullable = false)
	public Integer getIdorario() {
		return this.idorario;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "orario")
	public Set<People> getPeoples() {
		return this.peoples;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "orario")
	public Set<Ufficio> getUfficios() {
		return this.ufficios;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public void setIdorario(Integer idorario) {
		this.idorario = idorario;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	public void setUfficios(Set<Ufficio> ufficios) {
		this.ufficios = ufficios;
	}
	
	@Override
	public String toString() {
		return descrizione;
	}
}
