package it.drwolf.eloise.web.entity;

// Generated 17-giu-2008 14.55.38 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roletype generated by hbm2java
 */
@Entity
@Table(name = "`RoleType`", catalog = "eloise")
public class Roletype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5187456259840515943L;
	private Integer roleTypeId;
	private String role;
	private Set<Organizationalrole> organizationalroles = new HashSet<Organizationalrole>(
			0);

	public Roletype() {
	}

	public Roletype(String role, Set<Organizationalrole> organizationalroles) {
		this.role = role;
		this.organizationalroles = organizationalroles;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "roletype")
	public Set<Organizationalrole> getOrganizationalroles() {
		return this.organizationalroles;
	}

	@Column(name = "Role")
	public String getRole() {
		return this.role;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "RoleTypeID", unique = true, nullable = false)
	public Integer getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setOrganizationalroles(
			Set<Organizationalrole> organizationalroles) {
		this.organizationalroles = organizationalroles;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public void setRoleTypeId(Integer roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

}
