package it.drwolf.eloise.web.entity;

// Generated 17-giu-2008 14.55.38 by Hibernate Tools 3.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "`Sede`", catalog = "eloise")
public class Sede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3625865755909061881L;
	private Integer idsede;
	private String descrizione;
	private Set<Ufficio> ufficios = new HashSet<Ufficio>(0);
	private Set<People> peoples = new HashSet<People>(0);

	public Sede() {
	}

	public Sede(String descrizione, Set<Ufficio> ufficios, Set<People> peoples) {
		this.descrizione = descrizione;
		this.ufficios = ufficios;
		this.peoples = peoples;
	}

	@Column(name = "Descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDSede", unique = true, nullable = false)
	public Integer getIdsede() {
		return this.idsede;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<People> getPeoples() {
		return this.peoples;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<Ufficio> getUfficios() {
		return this.ufficios;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public void setIdsede(Integer idsede) {
		this.idsede = idsede;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	public void setUfficios(Set<Ufficio> ufficios) {
		this.ufficios = ufficios;
	}
	
	@Override
	public String toString() {
		return descrizione;
	}
	

}
