package it.drwolf.alerting.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * SitStrada generated by hbm2java
 */
@Entity
@Table(name = "SitCivico", catalog = "commercio_calenzano")
public class SitCivico implements java.io.Serializable {

	private static final long serialVersionUID = 6686297965909013348L;
	private Integer idSitCivico;
	private String numero;
	private String esponente;
	private String codice;
	private SitStrada sitStrada;

	public SitCivico() {
	}

	public SitCivico(Integer idSitCivico, String esponente, String numero,
			String codice, SitStrada sitstrada) {
		this.idSitCivico = idSitCivico;
		this.numero = numero;
		this.esponente = esponente;
		this.codice = codice;
		this.sitStrada = sitstrada;
	}

	public SitCivico(String esponente, String numero, String codice,
			SitStrada sitstrada) {
		this.numero = numero;
		this.esponente = esponente;
		this.codice = codice;
		this.sitStrada = sitstrada;
	}

	@Column(name = "codice", nullable = false)
	@NotNull
	public String getCodice() {
		return this.codice;
	}

	@Column(name = "esponente")
	public String getEsponente() {
		return this.esponente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDSitCivico", unique = true, nullable = false)
	public Integer getIdSitCivico() {
		return this.idSitCivico;
	}

	@Column(name = "numero", nullable = false)
	@NotNull
	public String getNumero() {
		return this.numero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSitStrada", nullable = false)
	@NotNull
	public SitStrada getSitStrada() {
		return this.sitStrada;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public void setEsponente(String esponente) {
		this.esponente = esponente;
	}

	public void setIdSitCivico(Integer idSitCivico) {
		this.idSitCivico = idSitCivico;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public void setSitStrada(SitStrada sitStrada) {
		this.sitStrada = sitStrada;
	}
}
