package it.drwolf.alerting.entity;

// Generated 17-giu-2008 14.53.44 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * SottotipoIntervento generated by hbm2java
 */
@Entity
@Table(name = "SottotipoIntervento", catalog = "segnalazioni")
public class SottotipoIntervento implements java.io.Serializable {

	private static final long serialVersionUID = -4961778282860178578L;
	private Integer id;
	private TipoIntervento tipoIntervento;
	private String descrizione;
	private Set<Intervento> interventos = new HashSet<Intervento>(0);

	public SottotipoIntervento() {
	}

	public SottotipoIntervento(TipoIntervento tipoIntervento) {
		this.tipoIntervento = tipoIntervento;
	}

	public SottotipoIntervento(TipoIntervento tipoIntervento,
			String descrizione, Set<Intervento> interventos) {
		this.tipoIntervento = tipoIntervento;
		this.descrizione = descrizione;
		this.interventos = interventos;
	}

	@Column(name = "Descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sottotipoIntervento")
	public Set<Intervento> getInterventos() {
		return this.interventos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoIntervento", nullable = false)
	@NotNull
	public TipoIntervento getTipoIntervento() {
		return this.tipoIntervento;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setInterventos(Set<Intervento> interventos) {
		this.interventos = interventos;
	}

	public void setTipoIntervento(TipoIntervento tipoIntervento) {
		this.tipoIntervento = tipoIntervento;
	}

}
