package it.drwolf.alerting.entity;

// Generated 17-giu-2008 14.53.44 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.CollectionOfElements;

/**
 * TipoIntervento generated by hbm2java
 */
@Entity
@Table(name = "TipoIntervento", catalog = "segnalazioni")
public class TipoIntervento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8086083052711225244L;
	private Integer id;
	private String descrizione;
	private List<SottotipoIntervento> sottotipoInterventos = new ArrayList<SottotipoIntervento>(
			0);

	private List<String> gestoriIntervento;

	private List<Stato> statiPossibili;

	public TipoIntervento() {
	}

	@Column(name = "Descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	@CollectionOfElements
	public List<String> getGestoriIntervento() {
		return this.gestoriIntervento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tipoIntervento")
	public List<SottotipoIntervento> getSottotipoInterventos() {
		return this.sottotipoInterventos;
	}

	@ManyToMany
	@OrderBy("descrizione")
	public List<Stato> getStatiPossibili() {
		return this.statiPossibili;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public void setGestoriIntervento(List<String> gestoriIntervento) {
		this.gestoriIntervento = gestoriIntervento;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setSottotipoInterventos(
			List<SottotipoIntervento> sottotipoInterventos) {
		this.sottotipoInterventos = sottotipoInterventos;
	}

	public void setStatiPossibili(List<Stato> statiPossibili) {
		this.statiPossibili = statiPossibili;
	}

}
