package it.drwolf.alerting.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipologiaToponimo generated by hbm2java
 */
@Entity
@Table(name = "TipologiaToponimo", catalog = "commercio_calenzano")
public class TipologiaToponimo implements java.io.Serializable {

	private static final long serialVersionUID = -7416347522722197853L;
	private Integer idTipologiaToponimo;
	private String descrizione;

	public TipologiaToponimo() {
	}

	public TipologiaToponimo(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "Descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTipologiaToponimo")
	public Integer getIdTipologiaToponimo() {
		return this.idTipologiaToponimo;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public void setIdTipologiaToponimo(Integer idTipologiaToponimo) {
		this.idTipologiaToponimo = idTipologiaToponimo;
	}

	public String toString() {
		return this.descrizione;
	}

}
